# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
email: gonzalo.chumillas@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Gonzalo Chumillas</h3><h1>Software Developer</h1><h3>Desarrollo de aplicaciones y sitios web</h3>PHP, jQuery, TypeScript, Python, Angular and much more..."



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gchumillas.github.io" # the base hostname & protocol for your site
twitter_username: Cequiel
github_username:  gchumillas

# Build settings
markdown: kramdown
